{
  "formatVersion": "1.1",
  "component": {
    "group": "co.invoid.android",
    "module": "demolibrary",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "oa7ss56lwvfbfjqf5k3h6xtvce"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "demolibrary-1.0.0.aar",
          "url": "demolibrary-1.0.0.aar",
          "size": 35320,
          "sha512": "782e07ae75d03a752ab314a905bdcefea0c90445006787956710c7cdab712741d2e760d1ac952067cb4106567c7db4eb73a95b235df89063cbd16701245b0a10",
          "sha256": "1853f7ee3846f2eb308296619edd438d3f14e02cb8a03481299e2bda68fdd4a6",
          "sha1": "63128bf28a6d063cfe682f29608faea50dc6dad4",
          "md5": "d1e235fa50fe3a472edcc4828c446bc9"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "demolibrary-1.0.0.aar",
          "url": "demolibrary-1.0.0.aar",
          "size": 35320,
          "sha512": "782e07ae75d03a752ab314a905bdcefea0c90445006787956710c7cdab712741d2e760d1ac952067cb4106567c7db4eb73a95b235df89063cbd16701245b0a10",
          "sha256": "1853f7ee3846f2eb308296619edd438d3f14e02cb8a03481299e2bda68fdd4a6",
          "sha1": "63128bf28a6d063cfe682f29608faea50dc6dad4",
          "md5": "d1e235fa50fe3a472edcc4828c446bc9"
        }
      ]
    }
  ]
}
